"""
Created on 2013-5-15
@author: Bobi Pu, bobi.pu@usc.edu
"""
WORD_INVALID_SENTENCE_FILTER = -1
WORD_FILTER = 0
WORD_CITE = 1
WORD_CAUSE_IN = 2
WORD_CAUSE_EX = 3
WORD_CONTROL_LOW = 4
WORD_CONTROL_HIGH = 5

MCD_POS = 6
MCD_NEG = 7
MCD_UNCERTAIN = 8

MAX_CONNECTION_SIZE = 150

TOTAL_CLUSTER = 2
BATCH_SIZE = 500

ENGAGER_CEO = 0
ENGAGER_ANALYST = 1

PFM_SENTENCE_WORD_COUNT_HIGH_LIMIT = 70
PFM_SENTENCE_WORD_COUNT_LOW_LIMIT = 15
PFM_SENTENCE_HYPHEN_LIMIT = 5
PFM_SENTENCE_DOLLAR_LIMIT = 4
PFM_SENTENCE_PERCENT_LIMIT = 4


END_OF_QUEUE = -1

#NLTK lemmatizer setting
ADJ, ADV, NOUN, VERB = 'a', 'r', 'n', 'v'

CITE_DISTANCE = 5
PFM_DISTANCE = 5

ANALYST_SURROUND_DISTANCE = 5

ARTICLE_EXPORT_CODE_SIZE = 5