"""
Created on 2013-5-15
@author: Bobi Pu, bobi.pu@usc.edu
"""

WORD_PFM = 0
WORD_POS = 1
WORD_NEG = 2

ATRB_NO = 3
ATRB_IN = 4
ATRB_EX = 5

CITE_WORD = 9

FILTER_WORD = 10
FILTER_PFM = 11

ENCODE_UTF8 = 'utf-8'
MAX_CONNECTION_SIZE = 150

TOTAL_CLUSTER = 2
BATCH_SIZE = 500

ENGAGER_CEO = 0
ENGAGER_ANALYST = 1

PFM_SENTENCE_WORD_COUNT_HIGH_LIMIT = 70
PFM_SENTENCE_WORD_COUNT_LOW_LIMIT = 15
PFM_SENTENCE_HYPHEN_LIMIT = 5
PFM_SENTENCE_DOLLAR_LIMIT = 4
PFM_SENTENCE_PERCENT_LIMIT = 4

#NLTK lemmatizer setting
ADJ, NOUN, VERB = 'a', 'n', 'v'


CITE_DISTANCE = 5
PFM_DISTANCE = 5

ANALYST_SURROUND_DISTANCE = 5

ARTICLE_EXPORT_CODE_SIZE = 5